#docker build -t qemu420 -f Dockerfile-qemu420 .
#docker run --rm -it -v $(pwd):/tmp/mount qemu420 cp /root/qemu420.tar.gz /tmp/mount

FROM ubuntu:18.04

RUN ln -fs /usr/share/zoneinfo/America/Phoenix /etc/localtime
RUN apt-get update && \
    apt-get install -y \
         git libfdt-dev libpixman-1-dev libssl-dev vim \
         socat libsdl2-dev libspice-server-dev autoconf libtool xtightvncviewer \
         tightvncserver x11vnc uuid-runtime uuid uml-utilities bridge-utils \
         python-dev liblzma-dev libc6-dev libegl1-mesa-dev libepoxy-dev libdrm-dev \
         libgbm-dev libaio-dev libusb-1.0.0-dev libgtk-3-dev bison  flex
RUN dpkg-reconfigure -f noninteractive tzdata


WORKDIR /root
RUN git clone https://git.qemu.org/git/qemu.git

WORKDIR /root/qemu
RUN git checkout v4.2.0
RUN git submodule update --init roms/seabios

RUN mkdir -p /tmp/qemu
RUN ./configure --prefix=/tmp/qemu \
--enable-kvm \
--disable-xen \
--enable-libusb \
--enable-debug-info \
--enable-debug \
--enable-sdl \
--enable-vhost-net \
--enable-spice \
--disable-debug-tcg \
--enable-opengl \
--enable-gtk \ 
--target-list=x86_64-softmmu \
--audio-drv-list=pa 

RUN make -j $(nproc)

#Build bios.bin
WORKDIR /root/qemu/roms/seabios
RUN make -j $(nproc)

#Build qemu
WORKDIR /root/qemu
RUN make install
RUN cp roms/seabios/out/bios.bin /tmp/qemu/bin/bios.bin

#Build OVMF.fd
RUN apt-get update && \
    apt-get install -y \
         uuid-dev nasm acpidump iasl bc 

RUN git submodule update --init --recursive roms/edk2
WORKDIR /root/qemu/roms/edk2
RUN /bin/bash -c "source ./edksetup.sh; make -C BaseTools/; build -b DEBUG -t GCC5 -a X64 -p OvmfPkg/OvmfPkgX64.dsc -D NETWORK_IP4_ENABLE -D NETWORK_ENABLE  -D SECURE_BOOT_ENABLE -DTPM2_ENABLE=TRUE"
RUN cp Build/OvmfX64/DEBUG_GCC5/FV/OVMF.fd /tmp/qemu/share/qemu/

WORKDIR /tmp
RUN tar -cvzf qemu420.tar.gz qemu 

WORKDIR /root
RUN cp /tmp/qemu420.tar.gz .



