# Pull QEMu source
sudo apt install -y git libfdt-dev libpixman-1-dev libssl-dev vim 
socat libsdl2-dev libspice-server-dev autoconf libtool xtightvncviewer 
tightvncserver x11vnc uuid-runtime uuid uml-utilities bridge-utils 
python-dev liblzma-dev libc6-dev libegl1-mesa-dev libepoxy-dev libdrm-
dev libgbm-dev libaio-dev libusb-1.0.0-dev libgtk-3-dev bison 
git clone https://git.qemu.org/git/qemu.git
cd qemu
git checkout v4.2.0
git submodule update --init roms/seabios
 
# configure that QEMU
./configure \
--prefix=/usr \
--enable-kvm \
--disable-xen \
--enable-libusb \
--enable-debug-info \
--enable-debug \
--enable-sdl \
--enable-vhost-net \
--enable-spice \
--disable-debug-tcg \
--enable-opengl \
--enable-gtk \
--target-list=x86_64-softmmu \
--audio-drv-list=pa
 
# build
make -j `nproc`
cd roms/seabios
make -j `nproc`
cd -
sudo make install
cp roms/seabios/out/bios.bin  ~/vm/fw
